services:
  demo-postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - demo-redis-network

  demo-redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - demo-redis-network

networks:
  demo-redis-network:
    driver: bridge