services:
  demo-backend:
    container_name: demo-backend-nestjs
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.docker
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - demo-postgres
      - demo-redis
    networks:
      - demo-redis-network

  demo-postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env.docker
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - demo-redis-network

  demo-redis:
    image: redis:alpine
    env_file:
      - .env.docker
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - demo-redis-network

networks:
  demo-redis-network:
    driver: bridge